### ISSUE TITLE
Failed to render markdown correctly

### ISSUE THREAD

**Issue by wiseodd** [talks-tue/talks.tue.flask#53] opened 2019-06-05 11:47 UTC
Input: `**NB:**`, expected output: **NB:**, reality: \*_NB_:\*
![Screenshot from 2019-06-05 13-43-18](https://user-images.githubusercontent.com/2296722/58954035-4a218400-8798-11e9-8cad-9745c9a97f70.png)
![Screenshot from 2019-06-05 13-45-20](https://user-images.githubusercontent.com/2296722/58954038-4beb4780-8798-11e9-9f6a-99acf7001cbf.png)

**Comment by fKunstner** [comment] 2019-06-05 11:55
I could fix it in the edit (see `/collection/4`, 4th element in `history`).
Apparently the Markdown processor interprets
* `**NB: **` as `<i>*NB :*</i>`
* `**NB:**` as `<b>NB:</b>`

**Comment by wiseodd** [comment] 2019-06-05 12:00
Follow up for links-behind-texts:
![Screenshot from 2019-06-05 13-59-01](https://user-images.githubusercontent.com/2296722/58954694-3414c300-879a-11e9-9cc4-50259e0b7bca.png)

**Comment by wiseodd** [comment] 2019-06-05 12:02
And MathJax doesn't seem to work in "Speaker's Bio"
![Screenshot from 2019-06-05 14-01-05](https://user-images.githubusercontent.com/2296722/58954813-7b02b880-879a-11e9-9f8d-0596a14728e1.png)

**Comment by fKunstner** [comment] 2019-06-05 12:11
> Follow up for links-behind-texts:
> ![Screenshot from 2019-06-05 13-59-01](https://user-images.githubusercontent.com/2296722/58954694-3414c300-879a-11e9-9cc4-50259e0b7bca.png)

Your link is broken, linking seem to work (see `/talk/3`)
```
[sample link with http](http://www.google.com)
[sample link without http](www.google.com)
[wiki link](https://en.wikipedia.org/wiki/Clarinet_Concerto_(Mozart))
[broken parenthesis link](https://en.wikipedia.org/wiki/Clarinet_Concerto_(Mozart) <- won't work
```

**Comment by fKunstner** [comment] 2019-06-05 12:17
> And MathJax doesn't seem to work in "Speaker's Bio"
> ![Screenshot from 2019-06-05 14-01-05](https://user-images.githubusercontent.com/2296722/58954813-7b02b880-879a-11e9-9f8d-0596a14728e1.png)

The math symbols work in the speaker's bio, but the syntax is a bit finicky. See `/talk/3`.

```
Mathjax samples

* dollar, space: $ f(x) = ||x||^2 $ # Doesn't work
* dollar, nospace: $f(x) = ||x||^2$ # Work
* paren, space: \( f(x) = ||x||^2 \) # Work
* paren, nospace:  \(f(x) = ||x||^2\) # Work

double dollar, nospace

$$f(x) = ||x||^2$$ # Work

double dollar, space

$$ f(x) = ||x||^2 $$ # Work
```

**Comment by tim-fi** [comment] 2019-06-06 13:02
Ah I missspoke in the meeting at the moment we are using [katex](https://katex.org/) to render the math parts. But I'll have to take a deep dive soon and make sure it renders things properly...

**Comment by tim-fi** [comment] 2019-08-15 14:58
> I could fix it in the edit (see `/collection/4`, 4th element in `history`).
> Apparently the Markdown processor interprets
> 
>     * `**NB: **` as `<i>*NB :*</i>`
> 
>     * `**NB:**` as `<b>NB:</b>`

Yeah the renderer is really iffy when it comes to spaces around stuff...

**Comment by tim-fi** [comment] 2019-08-19 19:22
I will close this issue for now, as the markdown rendering is working as intended as of now

**Closed by tim-fi** 2019-08-19 19:22 UTC
Labels: 🐛 bug, 🚧 planning
